[package]
name = "rs_static_lib_libc"
version = "0.1.0"
authors = ["Ömer Sinan Ağacan <omeragacan@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib", "staticlib"]

[dependencies]
libc = "0.2.73"
